### ISSUE TITLE
API URL for US1 region incorrect

### ISSUE THREAD

**Issue by justin-lachesky** [polarityio/sumo-logic#9]
When selecting the US1 region in the configuration, the API URL is set to `https://api.us1.sumologic.com` in the integration.js functions. At some point, SumoLogic changed the API endpoint for US1 to just `api.sumologic.com`. The other regions still follow the old convention, e.g. US2 is `api.us2.sumologic.com`.

Attempting to call API endpoints at the `api.us1.sumologic.com` domain will result in a 401 error.

**Comment by sarus** [comment]
Resolved as part of https://github.com/polarityio/sumo-logic/pull/11
